In [40]:
import pandas as pd

In [45]:
companies = pd.read_csv('companies.csv')
companies = companies.loc[[0,1,2]]
companies

  Ticker           Company
0   AAPL        Apple Inc.
1   NFLX     Netflix, Inc.
2   AMZN  Amazon.com, Inc.

In [39]:
# companies.to_csv('companies_clean.csv')

In [41]:
def get_tickers(path):
    companies = pd.read_csv(path)
    ticker_list = list(companies['Ticker'])
    print('Retrieved', str(len(ticker_list)), 'ticker symbols.')
    return ticker_list

get_tickers('companies_clean.csv')

Retrieved 3 ticker symbols.

['AAPL', 'NFLX', 'AMZN']

In [24]:
# import quandl
 
# def get_prices(ticker):
#     print('Retrieving data for', ticker)
#     prices = quandl.get('WIKI/' + ticker)['Adj. Close'].reset_index()
#     prices['Ticker'] = ticker
#     return prices
 
# data = []
 
# ticker_list = get_tickers('companies_clean.csv')
 
# for ticker in ticker_list:
#     prices = get_prices(ticker)
#     data.append(prices)

In [27]:
data = quandl.get_table('WIKI/PRICES', qopts = { 'columns': ['ticker', 'date', 'close'] }, ticker = ['NFLX'], date = { 'gte': '2000-01-01', 'lte': '2020-01-01' },  api_key='zb3EEjzwn8sgrXYUqyTD')
data

     ticker       date   close
None
0      NFLX 2018-03-27  300.69
1      NFLX 2018-03-26  320.35
2      NFLX 2018-03-23  300.94
3      NFLX 2018-03-22  306.70
4      NFLX 2018-03-21  316.48
5      NFLX 2018-03-20  317.50
6      NFLX 2018-03-19  313.48
7      NFLX 2018-03-16  318.45
8      NFLX 2018-03-15  321.09
9      NFLX 2018-03-14  321.55
10     NFLX 2018-03-13  315.88
11     NFLX 2018-03-12  321.30
12     NFLX 2018-03-09  331.44
13     NFLX 2018-03-08  317.00
14     NFLX 2018-03-07  321.16
15     NFLX 2018-03-06  325.22
16     NFLX 2018-03-05  315.00
17     NFLX 2018-03-02  301.05
18     NFLX 2018-03-01  290.39
19     NFLX 2018-02-28  291.38
20     NFLX 2018-02-27  290.61
21     NFLX 2018-02-26  294.16
22     NFLX 2018-02-23  285.93
23     NFLX 2018-02-22  278.14
24     NFLX 2018-02-21  281.04
25     NFLX 2018-02-20  278.55
26     NFLX 2018-02-16  278.52
27     NFLX 2018-02-15  280.27
28     NFLX 2018-02-14  266.00
29     NFLX 2018-02-13  258.27
...     ...        ...     ...
3958   NFLX 2002-07-05   17.87
3959   NFLX 2002-07-03   17.00
3960   NFLX 2002-07-02   16.42
3961   NFLX 2002-07-01   14.39
3962   NFLX 2002-06-28   13.99
3963   NFLX 2002-06-27   13.21
3964   NFLX 2002-06-26   13.84
3965   NFLX 2002-06-25   13.50
3966   NFLX 2002-06-24   13.70
3967   NFLX 2002-06-21   13.71
3968   NFLX 2002-06-20   13.40
3969   NFLX 2002-06-19   13.32
3970   NFLX 2002-06-18   12.75
3971   NFLX 2002-06-17   12.91
3972   NFLX 2002-06-14   13.81
3973   NFLX 2002-06-13   15.16
3974   NFLX 2002-06-12   15.30
3975   NFLX 2002-06-11   16.15
3976   NFLX 2002-06-10   16.19
3977   NFLX 2002-06-07   15.66
3978   NFLX 2002-06-06   16.55
3979   NFLX 2002-06-05   16.06
3980   NFLX 2002-06-04   15.65
3981   NFLX 2002-06-03   15.80
3982   NFLX 2002-05-31   15.07
3983   NFLX 2002-05-30   15.00
3984   NFLX 2002-05-29   15.45
3985   NFLX 2002-05-28   16.20
3986   NFLX 2002-05-24   16.94
3987   NFLX 2002-05-23   16.75

[3988 rows x 3 columns]

In [26]:
data = quandl.get_table('WIKI/PRICES', qopts = { 'columns': ['ticker', 'date', 'close'] }, ticker = ['AMZN'], date = { 'gte': '2020-01-01', 'lte': '2020-12-31' },  api_key='zb3EEjzwn8sgrXYUqyTD')
data

Empty DataFrame
Columns: [ticker, date, close]
Index: []

In [33]:
data = quandl.get_table('SHARADAR/SEP', qopts = { 'columns': ['ticker', 'date', 'close'] }, ticker = ['AAPL'], date = { 'gte': '2010-01-01', 'lte': '2010-11-01' },  api_key='zb3EEjzwn8sgrXYUqyTD')
data

Empty DataFrame
Columns: [ticker, date, close]
Index: []

In [42]:
quandl.get_table('SHARADAR/SEP', date={'gte':'2018-09-01', 'lte':'2018-12-31'}, ticker='AAPL', api_key='zb3EEjzwn8sgrXYUqyTD')

,ticker,date,open,high,low,close,volume,dividends,closeunadj,lastupdated
None,,,,,,,,,,
0,AAPL,2018-12-31,39.633,39.840,39.120,39.435,140013864.0,0.0,157.74,2020-08-31
1,AAPL,2018-12-28,39.375,39.630,38.638,39.057,169165696.0,0.0,156.23,2020-08-31
2,AAPL,2018-12-27,38.960,39.193,37.517,39.038,212468260.0,0.0,156.15,2020-08-31
3,AAPL,2018-12-26,37.075,39.307,36.680,39.292,234330176.0,0.0,157.17,2020-08-31
4,AAPL,2018-12-24,37.038,37.888,36.648,36.708,148676928.0,0.0,146.83,2020-08-31
5,AAPL,2018-12-21,39.215,39.540,37.407,37.682,382977536.0,0.0,150.73,2020-08-31
6,AAPL,2018-12-20,40.100,40.528,38.825,39.208,259091840.0,0.0,156.83,2020-08-31
7,AAPL,2018-12-19,41.500,41.862,39.773,40.222,196189188.0,0.0,160.89,2020-08-31
8,AAPL,2018-12-18,41.345,41.883,41.097,41.517,135366072.0,0.0,166.07,2020-08-31
9,AAPL,2018-12-17,41.362,42.087,40.682,40.985,177151688.0,0.0,163.94,2020-08-31
10,AAPL,2018-12-14,42.250,42.270,41.320,41.370,162814840.0,0.0,165.48,2020-08-31
11,AAPL,2018-12-13,42.623,43.142,42.388,42.737,127591308.0,0.0,170.95,2020-08-31
12,AAPL,2018-12-12,42.600,42.980,42.255,42.275,142510696.0,0.0,169.10,2020-08-31
13,AAPL,2018-12-11,42.915,42.947,41.750,42.157,189126660.0,0.0,168.63,2020-08-31
14,AAPL,2018-12-10,41.250,42.523,40.833,42.400,248103976.0,0.0,169.60,2020-08-31
15,AAPL,2018-12-07,43.373,43.623,42.075,42.123,169126524.0,0.0,168.49,2020-08-31
16,AAPL,2018-12-06,42.940,43.695,42.605,43.680,172393640.0,0.0,174.72,2020-08-31
17,AAPL,2018-12-04,45.237,45.597,44.068,44.172,165377128.0,0.0,176.69,2020-08-31
18,AAPL,2018-12-03,46.115,46.235,45.303,46.205,163192008.0,0.0,184.82,2020-08-31
19,AAPL,2018-11-30,45.072,45.083,44.258,44.645,158126196.0,0.0,178.58,2020-08-31
20,AAPL,2018-11-29,45.665,45.700,44.425,44.888,167079968.0,0.0,179.55,2020-08-31
21,AAPL,2018-11-28,44.182,45.322,43.733,45.235,184250156.0,0.0,180.94,2020-08-31
22,AAPL,2018-11-27,42.877,43.693,42.720,43.560,165549508.0,0.0,174.24,2020-08-31
23,AAPL,2018-11-26,43.560,43.737,42.565,43.655,179994080.0,0.0,174.62,2020-08-31
24,AAPL,2018-11-23,43.735,44.149,43.025,43.072,94495888.0,0.0,172.29,2020-08-31
25,AAPL,2018-11-21,44.932,45.068,44.138,44.195,124496840.0,0.0,176.78,2020-08-31
26,AAPL,2018-11-20,44.593,45.367,43.877,44.245,271300988.0,0.0,176.98,2020-08-31
27,AAPL,2018-11-19,47.500,47.675,46.248,46.465,167683488.0,0.0,185.86,2020-08-31
28,AAPL,2018-11-16,47.625,48.742,47.365,48.383,147713012.0,0.0,193.53,2020-08-31
29,AAPL,2018-11-15,47.097,47.992,46.725,47.852,185915204.0,0.0,191.41,2020-08-31
...,...,...,...,...,...,...,...,...,...,...
52,AAPL,2018-10-15,55.290,55.458,54.318,54.340,123164028.0,0.0,217.36,2020-08-31
53,AAPL,2018-10-12,55.105,55.720,54.210,55.528,161351404.0,0.0,222.11,2020-08-31
54,AAPL,2018-10-11,53.630,54.875,53.080,53.612,212497568.0,0.0,214.45,2020-08-31
55,AAPL,2018-10-10,56.365,56.587,54.013,54.090,167962216.0,0.0,216.36,2020-08-31
56,AAPL,2018-10-09,55.910,56.818,55.562,56.718,107564116.0,0.0,226.87,2020-08-31
57,AAPL,2018-10-08,55.553,56.200,55.050,55.943,118655692.0,0.0,223.77,2020-08-31
58,AAPL,2018-10-05,56.990,57.102,55.145,56.072,134321852.0,0.0,224.29,2020-08-31
59,AAPL,2018-10-04,57.695,58.087,56.682,56.998,128168000.0,0.0,227.99,2020-08-31
60,AAPL,2018-10-03,57.513,58.367,57.445,58.017,114619196.0,0.0,232.07,2020-08-31
61,AAPL,2018-10-02,56.813,57.500,56.657,57.320,99152680.0,0.0,229.28,2020-08-31
62,AAPL,2018-10-01,56.987,57.355,56.587,56.815,94403208.0,0.0,227.26,2020-08-31
63,AAPL,2018-09-28,56.197,56.460,56.005,56.435,91717456.0,0.0,225.74,2020-08-31
64,AAPL,2018-09-27,55.955,56.610,55.885,56.237,120724908.0,0.0,224.95,2020-08-31
65,AAPL,2018-09-26,55.250,55.938,54.940,55.105,95938824.0,0.0,220.42,2020-08-31
66,AAPL,2018-09-25,54.938,55.705,54.925,55.547,98217516.0,0.0,222.19,2020-08-31
67,AAPL,2018-09-24,54.205,55.315,54.157,55.197,110773432.0,0.0,220.79,2020-08-31
68,AAPL,2018-09-21,55.195,55.340,54.322,54.415,384986992.0,0.0,217.66,2020-08-31
69,AAPL,2018-09-20,55.060,55.570,54.788,55.008,106435176.0,0.0,220.03,2020-08-31
70,AAPL,2018-09-19,54.625,54.905,53.825,54.593,108495332.0,0.0,218.37,2020-08-31
71,AAPL,2018-09-18,54.447,55.462,54.280,54.560,126286848.0,0.0,218.24,2020-08-31
72,AAPL,2018-09-17,55.538,55.737,54.318,54.470,148780532.0,0.0,217.88,2020-08-31
73,AAPL,2018-09-14,56.438,56.710,55.630,55.960,127997156.0,0.0,223.84,2020-08-31
74,AAPL,2018-09-13,55.880,57.087,55.642,56.602,166825508.0,0.0,226.41,2020-08-31
75,AAPL,2018-09-12,56.235,56.250,54.960,55.267,197114960.0,0.0,221.07,2020-08-31
76,AAPL,2018-09-11,54.502,56.075,54.140,55.962,142996196.0,0.0,223.85,2020-08-31
77,AAPL,2018-09-10,55.237,55.462,54.117,54.583,158065812.0,0.0,218.33,2020-08-31
78,AAPL,2018-09-07,55.462,56.343,55.178,55.325,150479240.0,0.0,221.30,2020-08-31
79,AAPL,2018-09-06,56.557,56.837,55.325,55.775,137159904.0,0.0,223.10,2020-08-31
80,AAPL,2018-09-05,57.248,57.417,56.275,56.718,133331840.0,0.0,226.87,2020-08-31
81,AAPL,2018-09-04,57.102,57.295,56.657,57.090,109560528.0,0.0,228.36,2020-08-31